name: Push actions
on: [push]
jobs:
  Push-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Copy files
        run: | 
          cp -u -f ${GITHUB_WORKSPACE}/README.md ${GITHUB_WORKSPACE}/demo/index.md
    
      - name: Commit modified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub action: Push actions"
          branch: ${{ github.ref }}
